url: https://presente.github.io/mvp
baseurl: https://presente.github.io/mvp

# Site settings
title: Million Voters Project
email: info@millionvotersproject.org
description: "The goal of the Million Voter Project is to achieve a strategic change in the California Electorate to more closely reflect the diversity of its population."

# Partners names, titles and social links
partner:
- name: California Calls
  pic: 1
  url: http://cacalls.org
  # social:
  #   - title: twitter
  #     url: https://twitter.com/CAcalls
  #   - title: facebook
  #     url: https://www.facebook.com/CaliforniaCalls

- name: Presente.org
  pic: 2
  url: http://presente.org
  # social:
  #   - title: twitter
  #     url: https://twitter.com/presenteorg
  #   - title: facebook
  #     url: https://www.facebook.com/Presente.org/

- name: Mobilize the Immigrant Vote
  pic: 3
  url: http://www.mivcalifornia.org/
  # social:
  #   - title: twitter
  #     url: https://twitter.com/mivcalifornia
  #   - title: facebook
  #     url: https://www.facebook.com/mivcalifornia

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/millionvp
  - title: facebook
    url: https://www.facebook.com/millionvotersproject

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
# markdown: kramdown
# permalink: pretty
